name: Build and Push Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:build -Dimage=ghcr.io/imkunyoung/a-gateway

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: imkunyoung/aa-gateway
          username: ${{ github.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push imkunyoung/aa-gateway
