name: Application CI
on:
  push:
    branches: [ "master" ]
jobs:
  pipeline:
    name: Gateway pipeline
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
    timeout-minutes: 40
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
      JHI_DISABLE_WEBPACK_LOGS: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: chmod +x mvnw
        run: |
          chmod +x mvnw
#          npm run ci:backend:test
#      - name: Package application
#        run: npm run java:jar:prod
      - name: Build and publish docker image
        run: ./mvnw package -Pprod jib:build -Djib.to.image=imkunyoung/a-gateway -Djib.to.auth.username="${{ secrets.DOCKERHUB_USERNAME }}" -Djib.to.auth.password="${{ secrets.DOCKERHUB_TOKEN }}"

